В этой версии добавлена система отлова "полезных" ошибок. Вы тестируете функцию f, если аргумент не является целым числом, то f вызывает TypeError. Для проверки вызова ошибки вы получили возможность создавать "ошибочные" кейсы тестирования.

# Для копирования и проверки
def f(argument):
	error = type(argument) != int
	if not error:

		return argument
	
	elif error:
		raise TypeError('Type of argument is not int')

# Импорт модуля
from easytest import *

#
ftest = test (f)

# Создание обычных кейсов тестирования
ftest.case((1, {}), 1)
ftest.case((54373955291759, {}), 54373955291759)
# ...

# Создание "ошибочных" кейсов тестирования, обратите внимание на "error = True"
ftest.case((23.7, {}), error = True)
ftest.case(('Alexei Popovich, Dobrynya Nikitich, Ilya Muromets', {}), error = True)
# ...

# Запуск теста
ftest.todo()



Текст вывода:

OK
input:(1, {})
result:1
OK
input:(54373955291759, {})
result:54373955291759
OK
input:(23.7, {})
error:<class 'TypeError'>
OK
input:('Alexei Popovich, Dobrynya Nikitich, Ilya Muromets', {})
error:<class 'TypeError'>


